### ISSUE TITLE
Memory leak and CPU overclocking

### ISSUE THREAD

**Issue by DheerajDhamija14** [Vadim-Yelagin/DataSource#21]
I am using Datasource for my collection view to populate data.. If the number of cells to be used are less than a said amount it works well, but if it is very large, say 30k. UI hangs and CPU overclocking is observed. 

Code: 

 let optionsDataSource: MutableDataSource<TaskOptionCellModel>

self.optionsDataSource.replaceItems(with: Array(self.optionsCellModelForCurrentTask().prefix(100))) // Works well.. count is 100.

self.optionsDataSource.replaceItems(with: self.optionsCellModelForCurrentTask()) // CPU overclocking and memory leaks

self.optionsCellModelForCurrentTask() // count: 31000.

<img width="1034" alt="Screenshot 2019-09-18 at 12 57 35 PM" src="https://user-images.githubusercontent.com/37287616/65127115-d0469b00-da14-11e9-8581-fc762dc4f7cb.png">

Any help would be highly appreciated.

**Comment by stephanecopin** [comment]
Hey @DheerajDhamija14, thanks for the bug report!

I'm investigated a bit, and it seems like it's due to `MutableDataSource` using `reloadSections` to update its section, which `UITableView` then does computation to figure out`.
A few questions:
- Are you using `TableViewDataSource`?
- If so, are you animating the changes (the value of `TableViewDataSource`'s `animateChanges' property)? If so, you will need to disable that behavior as otherwise iOS will take too long too compute the row changes
I will submit a patch which will solve the performance for the case above, and in the meantime you can use the workaround below.

Put the following class in your project as a drop-in replacement for `DataSource`'s `MutableDataSource`:
```swift
final class SimpleMutableDataSource<T>: DataSource {
	let changes: Signal<DataChange, Never>
	private let observer: Signal<DataChange, Never>.Observer

	private let _items: MutableProperty<[T]>

	var items: Property<[T]> {
		return Property(_items)
	}

	let supplementaryItems: [String: Any]

	init(_ items: [T] = [], supplementaryItems: [String: Any] = [:]) {
		(self.changes, self.observer) = Signal<DataChange, Never>.pipe()
		self._items = MutableProperty(items)
		self.supplementaryItems = supplementaryItems
	}

	deinit {
		self.observer.sendCompleted()
	}

	let numberOfSections = 1

	func numberOfItemsInSection(_ section: Int) -> Int {
		return self._items.value.count
	}

	func supplementaryItemOfKind(_ kind: String, inSection section: Int) -> Any? {
		return self.supplementaryItems[kind]
	}

	func item(at indexPath: IndexPath) -> Any {
		return self._items.value[indexPath.item]
	}

	func leafDataSource(at indexPath: IndexPath) -> (DataSource, IndexPath) {
		return (self, indexPath)
	}

	func replaceItems(with items: [T]) {
		self._items.value = items
		let change = DataChangeReloadData()
		self.observer.send(value: change)
	}
}
```
and replace the `MutableDataSource` in your code with `SimpleMutableDataSource`.

Let me know how it goes!

**Comment by DheerajDhamija14** [comment]
Thanks for the update @stephanecopin. Yes I am using Collectiondatasource and this code works well, but I am not using any function to reload sections. 

Closing this issue. Thanks again for help.
